/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../store/database`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/date`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useMoodStats`; params?: Router.UnknownInputParams; } | { pathname: `/../services/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/../types/auth`; params?: Router.UnknownInputParams; } | { pathname: `/../store/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/../services/userService`; params?: Router.UnknownInputParams; } | { pathname: `/../services/familyService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/family` | `/family`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/entry/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../store/database`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/date`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useMoodStats`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/supabase`; params?: Router.UnknownOutputParams; } | { pathname: `/../types/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/../store/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/userService`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/familyService`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/family` | `/family`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/log` | `/log`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/entry/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../store/database${`?${string}` | `#${string}` | ''}` | `/../utils/date${`?${string}` | `#${string}` | ''}` | `/../hooks/useMoodStats${`?${string}` | `#${string}` | ''}` | `/../services/supabase${`?${string}` | `#${string}` | ''}` | `/../types/auth${`?${string}` | `#${string}` | ''}` | `/../store/AuthContext${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/../services/userService${`?${string}` | `#${string}` | ''}` | `/../services/familyService${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/family${`?${string}` | `#${string}` | ''}` | `/family${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/insights${`?${string}` | `#${string}` | ''}` | `/insights${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/log${`?${string}` | `#${string}` | ''}` | `/log${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../store/database`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/date`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useMoodStats`; params?: Router.UnknownInputParams; } | { pathname: `/../services/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/../types/auth`; params?: Router.UnknownInputParams; } | { pathname: `/../store/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/../services/userService`; params?: Router.UnknownInputParams; } | { pathname: `/../services/familyService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/family` | `/family`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/entry/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/entry/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
